source :gemcutter
gem 'rails', '2.3.8'
gem 'will_paginate', '2.3.12'
gem 'faker'
gem 'aws-s3'
gem 'actionmailer', '2.3.8'
gem 'actionpack', '2.3.8'
gem 'actionwebservice'
gem 'activerecord'
gem 'activeresource'
gem 'activesupport'
gem 'acts_as_ferret'
gem 'builder'
gem 'capistrano'
gem 'cgi_multipart_eof_fix'
gem 'columnize'
gem 'configuration'
gem 'daemons'
gem 'fastthread'
gem 'ferret'
gem 'gem_plugin'
gem 'heroku'
gem 'highline'
gem 'hpricot'
gem 'json'
gem 'json_pure'
gem 'launchy'
gem 'libxml-ruby'
gem 'linecache'
gem 'mime-types'
gem 'mongrel'
gem 'needle'
gem 'nokogiri'
gem 'rack', '1.1.0'
gem 'rake'
gem 'RedCloth'
gem 'rest-client'
gem 'ruby-debug'
gem 'ruby-debug-base'
gem 'ruby-openid'
gem 'ruby-yadis'
gem 'rubygems-update'
gem 'sqlite3-ruby'
gem 'sys-uname'
gem 'termios'
gem 'webrat'
gem 'xml-simple'
gem 'xmpp4r'
gem 'ZenTest'


