# DO NOT MODIFY THIS FILE
# Generated by Bundler 0.9.26

require 'digest/sha1'
require 'yaml'
require 'pathname'
require 'rubygems'
Gem.source_index # ensure Rubygems is fully loaded in Ruby 1.9

module Gem
  class Dependency
    if !instance_methods.map { |m| m.to_s }.include?("requirement")
      def requirement
        version_requirements
      end
    end
  end
end

module Bundler
  class Specification < Gem::Specification
    attr_accessor :relative_loaded_from

    def self.from_gemspec(gemspec)
      spec = allocate
      gemspec.instance_variables.each do |ivar|
        spec.instance_variable_set(ivar, gemspec.instance_variable_get(ivar))
      end
      spec
    end

    def loaded_from
      return super unless relative_loaded_from
      source.path.join(relative_loaded_from).to_s
    end

    def full_gem_path
      Pathname.new(loaded_from).dirname.expand_path.to_s
    end
  end

  module SharedHelpers
    attr_accessor :gem_loaded

    def default_gemfile
      gemfile = find_gemfile
      gemfile or raise GemfileNotFound, "Could not locate Gemfile"
      Pathname.new(gemfile)
    end

    def in_bundle?
      find_gemfile
    end

    def env_file
      default_gemfile.dirname.join(".bundle/environment.rb")
    end

  private

    def find_gemfile
      return ENV['BUNDLE_GEMFILE'] if ENV['BUNDLE_GEMFILE']

      previous = nil
      current  = File.expand_path(Dir.pwd)

      until !File.directory?(current) || current == previous
        filename = File.join(current, 'Gemfile')
        return filename if File.file?(filename)
        current, previous = File.expand_path("..", current), current
      end
    end

    def clean_load_path
      # handle 1.9 where system gems are always on the load path
      if defined?(::Gem)
        me = File.expand_path("../../", __FILE__)
        $LOAD_PATH.reject! do |p|
          next if File.expand_path(p).include?(me)
          p != File.dirname(__FILE__) &&
            Gem.path.any? { |gp| p.include?(gp) }
        end
        $LOAD_PATH.uniq!
      end
    end

    def reverse_rubygems_kernel_mixin
      # Disable rubygems' gem activation system
      ::Kernel.class_eval do
        if private_method_defined?(:gem_original_require)
          alias rubygems_require require
          alias require gem_original_require
        end

        undef gem
      end
    end

    def cripple_rubygems(specs)
      reverse_rubygems_kernel_mixin

      executables = specs.map { |s| s.executables }.flatten
      Gem.source_index # ensure RubyGems is fully loaded

     ::Kernel.class_eval do
        private
        def gem(*) ; end
      end

      ::Kernel.send(:define_method, :gem) do |dep, *reqs|
        if executables.include? File.basename(caller.first.split(':').first)
          return
        end
        opts = reqs.last.is_a?(Hash) ? reqs.pop : {}

        unless dep.respond_to?(:name) && dep.respond_to?(:requirement)
          dep = Gem::Dependency.new(dep, reqs)
        end

        spec = specs.find  { |s| s.name == dep.name }

        if spec.nil?
          e = Gem::LoadError.new "#{dep.name} is not part of the bundle. Add it to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        elsif dep !~ spec
          e = Gem::LoadError.new "can't activate #{dep}, already activated #{spec.full_name}. " \
                                 "Make sure all dependencies are added to Gemfile."
          e.name = dep.name
          e.version_requirement = dep.requirement
          raise e
        end

        true
      end

      # === Following hacks are to improve on the generated bin wrappers ===

      # Yeah, talk about a hack
      source_index_class = (class << Gem::SourceIndex ; self ; end)
      source_index_class.send(:define_method, :from_gems_in) do |*args|
        source_index = Gem::SourceIndex.new
        source_index.spec_dirs = *args
        source_index.add_specs(*specs)
        source_index
      end

      # OMG more hacks
      gem_class = (class << Gem ; self ; end)
      gem_class.send(:define_method, :bin_path) do |name, *args|
        exec_name, *reqs = args

        spec = nil

        if exec_name
          spec = specs.find { |s| s.executables.include?(exec_name) }
          spec or raise Gem::Exception, "can't find executable #{exec_name}"
        else
          spec = specs.find  { |s| s.name == name }
          exec_name = spec.default_executable or raise Gem::Exception, "no default executable for #{spec.full_name}"
        end

        gem_bin = File.join(spec.full_gem_path, spec.bindir, exec_name)
        gem_from_path_bin = File.join(File.dirname(spec.loaded_from), spec.bindir, exec_name)
        File.exist?(gem_bin) ? gem_bin : gem_from_path_bin
      end
    end

    extend self
  end
end

module Bundler
  ENV_LOADED   = true
  LOCKED_BY    = '0.9.26'
  FINGERPRINT  = "c9bada78c6bf5cdbf2895170b075bf672aad815d"
  HOME         = '/Users/Kyle/.bundle/ruby/1.8/bundler'
  AUTOREQUIRES = {:default=>[["rake", false], ["RedCloth", false], ["ZenTest", false], ["activesupport", false], ["rack", false], ["actionpack", false], ["actionmailer", false], ["activerecord", false], ["actionwebservice", false], ["activeresource", false], ["ferret", false], ["acts_as_ferret", false], ["builder", false], ["mime-types", false], ["xml-simple", false], ["aws-s3", false], ["highline", false], ["capistrano", false], ["cgi_multipart_eof_fix", false], ["columnize", false], ["configuration", false], ["daemons", false], ["faker", false], ["fastthread", false], ["gem_plugin", false], ["json_pure", false], ["launchy", false], ["rest-client", false], ["heroku", false], ["hpricot", false], ["json", false], ["libxml-ruby", false], ["linecache", false], ["mongrel", false], ["needle", false], ["nokogiri", false], ["rails", false], ["ruby-debug-base", false], ["ruby-debug", false], ["ruby-openid", false], ["ruby-yadis", false], ["rubygems-update", false], ["sqlite3-ruby", false], ["sys-uname", false], ["termios", false], ["webrat", false], ["will_paginate", false], ["xmpp4r", false]]}
  SPECS        = [
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rake-0.8.7/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rake-0.8.7.gemspec", :name=>"rake"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/RedCloth-4.2.3/lib", "/Library/Ruby/Gems/1.8/gems/RedCloth-4.2.3/ext", "/Library/Ruby/Gems/1.8/gems/RedCloth-4.2.3/lib/case_sensitive_require"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/RedCloth-4.2.3.gemspec", :name=>"RedCloth"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/ZenTest-4.3.3/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/ZenTest-4.3.3.gemspec", :name=>"ZenTest"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/activesupport-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/activesupport-2.3.8.gemspec", :name=>"activesupport"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rack-1.1.0/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rack-1.1.0.gemspec", :name=>"rack"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/actionpack-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/actionpack-2.3.8.gemspec", :name=>"actionpack"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/actionmailer-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/actionmailer-2.3.8.gemspec", :name=>"actionmailer"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/activerecord-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/activerecord-2.3.8.gemspec", :name=>"activerecord"},
        {:load_paths=>["/Users/Kyle/.bundle/ruby/1.8/gems/actionwebservice-0.6.0/lib"], :loaded_from=>"/Users/Kyle/.bundle/ruby/1.8/specifications/actionwebservice-0.6.0.gemspec", :name=>"actionwebservice"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/activeresource-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/activeresource-2.3.8.gemspec", :name=>"activeresource"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/ferret-0.11.6/lib"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/ferret-0.11.6.gemspec", :name=>"ferret"},
        {:load_paths=>["/Users/Kyle/.bundle/ruby/1.8/gems/acts_as_ferret-0.4.7/lib"], :loaded_from=>"/Users/Kyle/.bundle/ruby/1.8/specifications/acts_as_ferret-0.4.7.gemspec", :name=>"acts_as_ferret"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/builder-2.1.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/builder-2.1.2.gemspec", :name=>"builder"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/mime-types-1.16/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/mime-types-1.16.gemspec", :name=>"mime-types"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/xml-simple-1.0.12/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/xml-simple-1.0.12.gemspec", :name=>"xml-simple"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/aws-s3-0.6.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/aws-s3-0.6.2.gemspec", :name=>"aws-s3"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/highline-1.5.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/highline-1.5.2.gemspec", :name=>"highline"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/net-ssh-2.0.23/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/net-ssh-2.0.23.gemspec", :name=>"net-ssh"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/net-scp-1.0.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/net-scp-1.0.2.gemspec", :name=>"net-scp"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/net-sftp-2.0.4/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/net-sftp-2.0.4.gemspec", :name=>"net-sftp"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/net-ssh-gateway-1.0.1/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/net-ssh-gateway-1.0.1.gemspec", :name=>"net-ssh-gateway"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/capistrano-2.5.19/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/capistrano-2.5.19.gemspec", :name=>"capistrano"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/cgi_multipart_eof_fix-2.5.0/lib"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/cgi_multipart_eof_fix-2.5.0.gemspec", :name=>"cgi_multipart_eof_fix"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/columnize-0.3.1/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/columnize-0.3.1.gemspec", :name=>"columnize"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/configuration-1.1.0/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/configuration-1.1.0.gemspec", :name=>"configuration"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/daemons-1.1.0/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/daemons-1.1.0.gemspec", :name=>"daemons"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/faker-0.3.1/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/faker-0.3.1.gemspec", :name=>"faker"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/fastthread-1.0.7/lib", "/Library/Ruby/Gems/1.8/gems/fastthread-1.0.7/ext"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/fastthread-1.0.7.gemspec", :name=>"fastthread"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/gem_plugin-0.2.3/lib"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/gem_plugin-0.2.3.gemspec", :name=>"gem_plugin"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/json_pure-1.4.3/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/json_pure-1.4.3.gemspec", :name=>"json_pure"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/launchy-0.3.5/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/launchy-0.3.5.gemspec", :name=>"launchy"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rest-client-1.4.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rest-client-1.4.2.gemspec", :name=>"rest-client"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/heroku-1.9.11/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/heroku-1.9.11.gemspec", :name=>"heroku"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/hpricot-0.8.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/hpricot-0.8.2.gemspec", :name=>"hpricot"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/json-1.4.3/ext/json/ext", "/Library/Ruby/Gems/1.8/gems/json-1.4.3/ext", "/Library/Ruby/Gems/1.8/gems/json-1.4.3/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/json-1.4.3.gemspec", :name=>"json"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/libxml-ruby-1.1.4/lib", "/Library/Ruby/Gems/1.8/gems/libxml-ruby-1.1.4/ext/libxml"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/libxml-ruby-1.1.4.gemspec", :name=>"libxml-ruby"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/linecache-0.43/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/linecache-0.43.gemspec", :name=>"linecache"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/lib", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/mongrel-1.1.5/ext"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/mongrel-1.1.5.gemspec", :name=>"mongrel"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/needle-1.3.0/lib"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/needle-1.3.0.gemspec", :name=>"needle"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/nokogiri-1.4.2/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/nokogiri-1.4.2.gemspec", :name=>"nokogiri"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rack-test-0.5.4/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rack-test-0.5.4.gemspec", :name=>"rack-test"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rails-2.3.8/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rails-2.3.8.gemspec", :name=>"rails"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/ruby-debug-base-0.10.3/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/ruby-debug-base-0.10.3.gemspec", :name=>"ruby-debug-base"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/ruby-debug-0.10.3/cli"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/ruby-debug-0.10.3.gemspec", :name=>"ruby-debug"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/ruby-openid-2.1.7/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/ruby-openid-2.1.7.gemspec", :name=>"ruby-openid"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/ruby-yadis-0.3.4/lib"], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/ruby-yadis-0.3.4.gemspec", :name=>"ruby-yadis"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/rubygems-update-1.3.7/hide_lib_for_update"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/rubygems-update-1.3.7.gemspec", :name=>"rubygems-update"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/sqlite3-ruby-1.3.0/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/sqlite3-ruby-1.3.0.gemspec", :name=>"sqlite3-ruby"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/sys-uname-0.8.4/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/sys-uname-0.8.4.gemspec", :name=>"sys-uname"},
        {:load_paths=>["/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/termios-0.9.4/lib", "/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/gems/termios-0.9.4/."], :loaded_from=>"/System/Library/Frameworks/Ruby.framework/Versions/1.8/usr/lib/ruby/gems/1.8/specifications/termios-0.9.4.gemspec", :name=>"termios"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/webrat-0.7.1/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/webrat-0.7.1.gemspec", :name=>"webrat"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/will_paginate-2.3.12/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/will_paginate-2.3.12.gemspec", :name=>"will_paginate"},
        {:load_paths=>["/Library/Ruby/Gems/1.8/gems/xmpp4r-0.5/lib"], :loaded_from=>"/Library/Ruby/Gems/1.8/specifications/xmpp4r-0.5.gemspec", :name=>"xmpp4r"},
      ].map do |hash|
    if hash[:virtual_spec]
      spec = eval(hash[:virtual_spec], TOPLEVEL_BINDING, "<virtual spec for '#{hash[:name]}'>")
    else
      dir = File.dirname(hash[:loaded_from])
      spec = Dir.chdir(dir){ eval(File.read(hash[:loaded_from]), TOPLEVEL_BINDING, hash[:loaded_from]) }
    end
    spec.loaded_from = hash[:loaded_from]
    spec.require_paths = hash[:load_paths]
    if spec.loaded_from.include?(HOME)
      Bundler::Specification.from_gemspec(spec)
    else
      spec
    end
  end

  extend SharedHelpers

  def self.configure_gem_path_and_home(specs)
    # Fix paths, so that Gem.source_index and such will work
    paths = specs.map{|s| s.installation_path }
    paths.flatten!; paths.compact!; paths.uniq!; paths.reject!{|p| p.empty? }
    ENV['GEM_PATH'] = paths.join(File::PATH_SEPARATOR)
    ENV['GEM_HOME'] = paths.first
    Gem.clear_paths
  end

  def self.match_fingerprint
    lockfile = File.expand_path('../../Gemfile.lock', __FILE__)
    lock_print = YAML.load(File.read(lockfile))["hash"] if File.exist?(lockfile)
    gem_print = Digest::SHA1.hexdigest(File.read(File.expand_path('../../Gemfile', __FILE__)))

    unless gem_print == lock_print
      abort 'Gemfile changed since you last locked. Please run `bundle lock` to relock.'
    end

    unless gem_print == FINGERPRINT
      abort 'Your bundled environment is out of date. Run `bundle install` to regenerate it.'
    end
  end

  def self.setup(*groups)
    match_fingerprint
    clean_load_path
    cripple_rubygems(SPECS)
    configure_gem_path_and_home(SPECS)
    SPECS.each do |spec|
      Gem.loaded_specs[spec.name] = spec
      spec.require_paths.each do |path|
        $LOAD_PATH.unshift(path) unless $LOAD_PATH.include?(path)
      end
    end
    self
  end

  def self.require(*groups)
    groups = [:default] if groups.empty?
    groups.each do |group|
      (AUTOREQUIRES[group.to_sym] || []).each do |file, explicit|
        if explicit
          Kernel.require file
        else
          begin
            Kernel.require file
          rescue LoadError
          end
        end
      end
    end
  end

  # Set up load paths unless this file is being loaded after the Bundler gem
  setup unless defined?(Bundler::GEM_LOADED)
end
